version: 2

sources:

  # Airbyte source
  - name: airbyte_staging
    description: "Data ingested by Airbyte from PostgreSQL"
    database: MinIO_Airbyte_Staging
    schema: "airbyte-staging"
    
    tables:
      - name: data_customers
        description: "Customers data synced via Airbyte"
        identifier: data/customers
        columns:
          - name: id
            description: "Customer ID"
            tests:
              - not_null
              - unique
          
          - name: first_name
            description: "Customer first name"
          
          - name: last_name
            description: "Customer last name"
          
          - name: email
            description: "Customer email"
            tests:
              - not_null
          
          - name: created_at
            description: "Customer creation timestamp"
          
          - name: _airbyte_ab_id
            description: "Airbyte internal ID"
            tests:
              - not_null
          
          - name: _airbyte_emitted_at
            description: "Timestamp when Airbyte emitted the record"
            tests:
              - not_null
      
      - name: data_orders
        description: "Orders data synced via Airbyte"
        identifier: data/orders
        columns:
          - name: id
            description: "Order ID"
            tests:
              - not_null
              - unique
          
          - name: customer_id
            description: "Foreign key to customers"
            tests:
              - not_null
          
          - name: order_date
            description: "Order date"
          
          - name: total_amount
            description: "Order total amount"
          
          - name: status
            description: "Order status"
          
          - name: _airbyte_ab_id
            description: "Airbyte internal ID"
            tests:
              - not_null
          
          - name: _airbyte_emitted_at
            description: "Timestamp when Airbyte emitted the record"
            tests:
              - not_null
