# Configuration OpenMetadata pour le connecteur Dremio
# Avec support du profiling et auto-classification

source:
  type: dremio
  serviceName: dremio_local
  serviceConnection:
    config:
      type: Dremio
      # Connexion Dremio via connectionOptions
      connectionOptions:
        url: "http://localhost:9047"
        username: "admin"
        password: "admin123"
  
  sourceConfig:
    config:
      # Type de workflow (metadata ou profiler)
      type: DatabaseMetadata
      
      # ============================================
      # PROFILING CONFIGURATION
      # ============================================
      # Nombre de lignes à échantillonner pour le profiling
      # Par défaut: toutes les lignes (peut être lent sur grandes tables)
      # Recommandé: 1000 à 10000 pour un bon équilibre performance/précision
      profileSampleRows: 5000
      
      # Activer le profiling automatique
      # enableProfiling: true
      
      # ============================================
      # AUTO-CLASSIFICATION CONFIGURATION
      # ============================================
      # Activer l'auto-classification des colonnes (détection PII)
      # enableAutoClassification: true
      
      # ============================================
      # FILTERS (Optional)
      # ============================================
      # Filtrer les sources à ingérer
      # databaseFilterPattern:
      #   includes:
      #     - "MinIO_.*"
      #     - "Samples"
      
      # Filtrer les schémas
      # schemaFilterPattern:
      #   excludes:
      #     - "sys"
      #     - "INFORMATION_SCHEMA"
      
      # Filtrer les tables
      # tableFilterPattern:
      #   includes:
      #     - ".*customers.*"
      #     - ".*orders.*"

# Configuration du sink (destination OpenMetadata)
sink:
  type: metadata-rest
  config:
    # URL de l'API OpenMetadata
    openMetadataServerConfig:
      hostPort: "http://localhost:8585/api"
      authProvider: openmetadata
      securityConfig:
        jwtToken: "YOUR_JWT_TOKEN_HERE"

# Configuration du workflow
workflowConfig:
  # Activer les logs de debug
  loggerLevel: INFO
  # Activer les métriques OpenMetadata
  openMetadataServerConfig:
    hostPort: "http://localhost:8585/api"
    authProvider: openmetadata
    securityConfig:
      jwtToken: "YOUR_JWT_TOKEN_HERE"
