source:
  type: custom-dremio
  serviceName: Dremio Data Lake Platform
  serviceConnection:
    config:
      type: CustomDatabase
      sourcePythonClass: dremio_connector.core.dremio_source.DremioSource
      connectionOptions:
        # Dremio Connection Settings
        dremioHost: localhost
        dremioPort: "9047"
        dremioProtocol: http
        dremioUsername: admin
        dremioPassword: admin123
        dremioApiVersion: v3
        
        # Ingestion Options
        include_sources: "true"
        include_vds: "true"
        include_pds: "true"
        include_spaces: "true"
        
        # Filter Patterns (regex)
        source_filter_pattern: ".*"
        source_exclude_pattern: "tmp_.*|test_.*"
        vds_filter_pattern: ".*"
        vds_exclude_pattern: "tmp_.*|debug_.*"
        
        # Metadata Options
        include_column_descriptions: "true"
        include_table_descriptions: "true"
        include_lineage: "true"
        include_tags: "true"
        
        # Tag Mapping (format: "keyword:TagFQN;keyword:TagFQN")
        tag_mapping: "raw:Tier.Bronze;curated:Tier.Silver;analytics:Tier.Gold"
        default_tags: "Source.Dremio"
        
        # Batch Processing
        batch_size: "50"
        timeout: "60"

  sourceConfig:
    config:
      type: DatabaseMetadata
      # Additional database metadata configuration

sink:
  type: metadata-rest
  config: {}

workflowConfig:
  loggerLevel: INFO
  openMetadataServerConfig:
    hostPort: http://localhost:8585/api
    authProvider: openmetadata
    securityConfig:
      # IMPORTANT: Generate a valid JWT token from OpenMetadata UI
      # Settings -> Bots -> ingestion-bot -> Generate New Token
      jwtToken: "eyJraWQiOiJHYjM4OWEtOWY3Ni1nZGpzLWE5MmotMDI0MmJrOTQzNTYiLCJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJvcGVuLW1ldGFkYXRhLm9yZyIsInN1YiI6ImluZ2VzdGlvbi1ib3QiLCJyb2xlcyI6WyJJbmdlc3Rpb25Cb3RSb2xlIl0sImVtYWlsIjoiaW5nZXN0aW9uLWJvdEBvcGVuLW1ldGFkYXRhLm9yZyIsImlzQm90Ijp0cnVlLCJ0b2tlblR5cGUiOiJCT1QiLCJpYXQiOjE3NTE0ODU5OTksImV4cCI6bnVsbH0.csOeKzpzZWFIvCP9JgomVyea7Rqbs-FkPywzaZi5oIo34szgOuN_d6Kz69IT3F-NhPE0MJjVEe7K61X89duKX9TjBUm7SuTPq27OYfanvZp-28xL4QTAryeXwzVrGCDH0q-6ZqONIvBcwk8HNONH474hjT1q0hpwtrUZx9PW9L3JzrBR60P316H8QpDNVvDVMQLsyLBRClZdpqPDXX5zsXEANVSZC6G_R6Dkh0MBtgOAeURvdcRkINwPsvgfq-flTjsJM-tUUNxasfgKed25zMAXqbQP542ctY3BYvhhtWxn-gvgztg_gRlwy2fMrC6hFmNYXLt2lqwHgIuqE-drgw"
